name: Node.js Package CI/CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx cross-env NODE_OPTIONS=--experimental-vm-modules npm test

      - name: Build Package
        run: npx tsup src/index.ts --format esm,cjs --dts

      - name: Sync package.json version with tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./package.json').version")

          echo "Tag version: $TAG_VERSION"
          echo "Package.json version: $PKG_VERSION"

          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "Updating package.json version..."
            npm version $TAG_VERSION --no-git-tag-version
          else
            echo "package.json already at version $PKG_VERSION, skipping update."
          fi

      - name: Debug ref
        run: echo "Github ref is $GITHUB_REF"

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
