name: Node.js Package CI/CD

on:
  push:
    tags:
      - "v*"           # Trigger on any tag like v1.0.1
  workflow_dispatch:    # Optional: manually trigger workflow from GitHub

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx cross-env NODE_OPTIONS=--experimental-vm-modules npm test

      - name: Build Package
        run: npx tsup src/index.ts --format esm,cjs --dts

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')  # only publish on tag
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
